config/routes.rb
Rails.application.routes.draw do

  resources :likes
  resources :users
  resources :links

  root 'links#index'

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :link
  belongs_to :user
end

app/models/link.rb
class Link < ActiveRecord::Base
  has_many :likes
  belongs_to :user

  validates :title, presence: true
  validates :link, presence: true
  validates :user_id, presence: true

  def Link.sort_links
    joins(:likes)
      .group("link_id")
      .order("COUNT(likes.id) DESC")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :likes
  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new
    @like.link_id = params[:link_id]
    @like.feels = params[:feels]
    @like.user_id = rand(1..30)

    @like.save
    redirect_to :back
  end

  def new
  end

  def destroy
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    page_set
    sorted = Link.sort_links
    @links = sorted.offset(@offset).limit(20)
  end

  def create
    @link = Link.new
    @link.title = params[:link][:title]
    @link.link = params[:link][:link]
    @link.user_id = params[:link][:user_id]

    if @link.save
      redirect_to link_path(@link.id), notice: "Success!"
    else
      flash[:alert] = "Error Occured! Link couldn't be created!"
      render :new
    end
  end

  def new
    @link = Link.new
  end

  def destroy
  end

  def show
    @link = Link.find(params["id"])
  end

  def page_set
    if params[:page].nil?
      @page = 1
    else
      @page = params[:page].to_i
    end
    if @page > 0
      @offset = @page * 20
    else
      @offset = 0
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new
    @user.name = params[:user][:name]
    @user.email = params[:user][:email]
    @user.profile_pic = params[:user][:profile_pic]

    if @user.save
      redirect_to user_path(@user.id), notice: "Success!"
    else
      flash[:alert] = "Error Occured! User couldn't be created!"
      render :new
    end
  end

  def destroy
  end

  def index
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params["id"])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/links_helper.rb
module LinksHelper

  def link_temp_block

  end

  def get_temp(link)
    link.likes.where(feels: 1).count - link.likes.where(feels: 0).count
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Redditapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
      <a href="http://localhost:3000/">
        <div class="top-bar-home">
        <p>Home</p>
      </div></a>
      <a href="http://localhost:3000/#">
        <div class="top-bar-users">
        <p>Users</p>
      </div></a>
      <a href="http://localhost:3000/links">
        <div class="top-bar-links">
        <p>Links</p>
      </div></a>
      <a href="http://localhost:3000/links/new">
        <div class="top-bar-new-link">
        <p>New Link</p>
      </div></a>
      <div class= "top-bar-search">
        <%= form_tag("/search", method: "get") do %>
          <!-- <%= label_tag(:q, "Search for:") %> -->
          <%= text_field_tag(:q) %>
          <%= submit_tag("Search") %>
        <% end %>
      </div>
    </header>

<%= flash[:alert] %>
<%= flash[:notice] %>

<div class= "container">
<%= yield %>
</div>
</body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/likes/new.html.erb
<h1>Likes#new</h1>
<p>Find me in app/views/likes/new.html.erb</p>

app/views/links/create.html.erb
<h1>Links#create</h1>
<p>Find me in app/views/links/create.html.erb</p>

app/views/links/destroy.html.erb
<h1>Links#destroy</h1>
<p>Find me in app/views/links/destroy.html.erb</p>

app/views/links/index.html.erb
<h1>Links#index</h1>
<% @links.each do |x|%>
<hr>
<% temp = get_temp(x) %>
👍: <%=x.likes.where(feels: 1).count%>
👎: <%=x.likes.where(feels: 0).count%>
<% if temp > 1 %>
  🔥: <%=temp%>
<% else %>
  💩: <%=temp%>
<% end %>
<a href = "http://localhost:3000/links/<%=x.id%>">
<%=x.title.capitalize%></a><br>
<div class = "feels_bar">
<%= button_to 'Love', likes_path(link_id: x.id, feels: 1), method: :post, form_class: "feelings" %>
<%= button_to 'Hate', likes_path(link_id: x.id, feels: 0), method: :post, form_class: "feelings" %>
</div>
<br>
<%end%>
<div class = "page_bar">
  <a href="http://localhost:3000/links?page=<%=@page - 1%>">
    <div>
    <p>Previous</p>
  </div></a>
  <a href="http://localhost:3000/links?page=<%=@page + 1%>">
    <div>
    <p>Next</p>
  </div></a>
</div>

app/views/links/new.html.erb
<h1>Links#new</h1>


<div class='row'>
  <div class='twelve columns'>
    <%= form_for(@link) do |f| %>
      <div class='row'>
        <div class='three columns'>
          <%= f.label :title %>
          <%= f.text_field :title, class: 'input-field title', placeholder: "Insert Link Title" %>
        </div>
        <div class='three columns'>
          <%= f.label :link %>
          <%= f.text_field :link, class: 'input-field link', placeholder: "Insert Link URL HERE" %>
        </div>
        <div class='three columns'>
          <%= f.label :user_id %>
          <%= f.number_field(:user_id, in: 1..30) %>
        </div>
      </div>
      <div class='row'>
        <%= f.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/links/show.html.erb
<h1>Links#show</h1>
<h2><%=@link.title%></h2>
<div>
  Likes: <%=@link.likes.where(feels: 1).count%>
  Dislikes: <%=@link.likes.where(feels: 0).count%>
  Temperature: <%=(@link.likes.where(feels: 1).count) - (@link.likes.where(feels: 0).count)%>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>


<div class='row'>
  <div class='twelve columns'>
    <%= form_for(@user) do |f| %>
      <div class='row'>
        <div class='three columns'>
          <%= f.label :name %>
          <%= f.text_field :name, class: 'input-field title', placeholder: "Master Namington" %>
        </div>
        <div class='three columns'>
          <%= f.label :email %>
          <%= f.text_field :email, class: 'input-field link', placeholder: "YourAddress@Email.Com" %>
        </div>
        <div class='three columns'>
          <%= f.label :profile_pic %>
          <%= f.number_field(:profile_pic, in: 1..15) %>
        </div>
      </div>
      <div class='row'>
        <%= f.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<h2><%=@user.name%></h2>
<div>
    Email: <%= @user.email %>
</div>